version: "3"

services:
  elm:
    build:
      context: docker/elm
      dockerfile: Dockerfile
      args:
        ELM_VERSION: $ELM_VERSION
        ELM_DISTRIBUTION: $ELM_DISTRIBUTION
        NODEJS_VERSION: $NODEJS_VERSION
        NODEJS_DISTRIBUTION: $NODEJS_DISTRIBUTION
        SERVER_PORT: $SERVER_PORT
        SERVER_HOST: $SERVER_HOST
    ports:
      - $SERVER_HOST:$SERVER_PORT:$SERVER_PORT
    env_file: .env
    volumes:
      - .:/home/elm

  npm:
    extends: elm
    entrypoint: npm
